### ISSUE TITLE
ChangeType not working for typealias

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#48]
I am using `ChangeType` to rewrite `Validated` to `Either`, and it's not working for following case. (It's perhaps a bit far-fetched and wasn't expecting this to work, but implementing a custom `ChangeType` seems tricky so hoping we can perhaps find an intermediate solution).

I currently have following typealiases:

```kotlin
typealias ValidatedNel<E, A> = Validated<NonEmptyList<A>, E>
typealias EitherNel<E, A> = Either<NonEmptyList<A>, E>
```

And following setting in my `yml`:

```yml
- org.openrewrite.java.ChangeType:
    oldFullyQualifiedTypeName: arrow.core.Validated
    newFullyQualifiedTypeName: arrow.core.Either
```

I was hoping it would rewrite:

```kotlin
val x: ValidatedNel<String, Int> = TODO()
```

to

```kotlin
val x: Either<NonEmptyList<String>, Int> = TODO()
```

Ideally would be a way to rewrite from `ValidatedNel<E, A>` to `EitherNel<E, A>` but it's not at all blocking.
I also tried following, but naturally it didn't do anything 😁 

```yml
- org.openrewrite.java.ChangeType:
    oldFullyQualifiedTypeName: arrow.core.ValidatedNel
    newFullyQualifiedTypeName: arrow.core.Either
```

**Comment by nomisRev** [comment]
I was however able to rewrite a `type` to a `typealias` using `ChangeType`. Following rewrite worked:

```yml
- org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: arrow.core.continuations.Effect
      newFullyQualifiedTypeName: arrow.core.raise.Effect
```

for following code

```kotlin
package arrow.core.continuations

interface Effect<E, A>
```

and

```kotlin
package arrow.core.raise

typealias Effect<E, A> = suspend Raise<E>.() -> A
```
